### ISSUE TITLE
🚚  Demo | Hide the Vercel Deployment URL

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/quick-edit-demo#11]
cc's: @wicksipedia @Marxoz @adamcogan 

### Pain

The link to the demo on the homepage isn't clear it'll take you to a demo.
Additionally, clicking to the demo on the homepage makes it look like it's taking you to a new site – not still in tina.io.

### Suggested Solution

- Change the button text going to the demo to "Demo our live editor", or other
- Use something like [next.js rewrites](https://vercel.com/guides/how-can-i-serve-multiple-projects-under-a-single-domain#with-next.js-multi-zones-) to put the current URL https://quick-edit-demo.vercel.app/admin#/~ to tina.io/demo
(or similar)

### Tasks

- [ ] Make a PR for changing the button text on the home page for the demo button
- [x] Investigate how to rewrite the quick edit demo url on redirect (ex. to tina.io/demo)
- [x] If it can be done without deployment changes, make the change.
- [x] Create a PR for the change
- [ ] Get the copy and new URL approved by both Landon and Gert

**Comment by joshbermanssw** [comment]
Changed the demo url to demo.tina.io

**Comment by joshbermanssw** [comment]
Ignored both tasks to change the button text - these changes need to go through a series of people.  Moved into https://github.com/tinacms/tina.io/issues/2493
